services:
  mysql:
    image: mysql:8.0
    container_name: sql_volunteer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volunteer_platform
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    command: ["mysqld", "--bind-address=0.0.0.0"]
    networks:
      - app-network

  server:
    image: iromanchuk06/volunteer_server:latest
    build:
      context: .
      dockerfile: modules/server/Dockerfile
    container_name: volunteer_server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/volunteer_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_ENDPOINT: http://server:8080
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 60s
    ports:
        - "8080:8080"
    networks:
      - app-network

  client:
    image: iromanchuk06/volunteer_client:latest
    environment:
      - SERVER_ENDPOINT=http://server:8080
    build:
      context: .
      dockerfile: modules/client/Dockerfile
    container_name: volunteer_client
    depends_on:
      server:
        condition: service_healthy
    tty: true
    stdin_open: true
    entrypoint: ["java", "-jar", "/app/client.jar"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: